export const MOVIE_TOP_REQUEST = 'MOVIE_TOP_REQUEST';
export const MOVIE_TOP_SUCCESS = 'MOVIE_TOP_SUCCESS';
export const MOVIE_TOP_FAIL = 'MOVIE_TOP_FAIL';

export const MOVIE_POPULAR_REQUEST = 'MOVIE_POPULAR_REQUEST';
export const MOVIE_POPULAR_SUCCESS = 'MOVIE_POPULAR_SUCCESS';
export const MOVIE_POPULAR_FAIL = 'MOVIE_POPULAR_FAIL';
