export const SHOW_TOP_REQUEST = 'SHOW_TOP_REQUEST';
export const SHOW_TOP_SUCCESS = 'SHOW_TOP_SUCCESS';
export const SHOW_TOP_FAIL = 'SHOW_TOP_FAIL';

export const SHOW_POPULAR_REQUEST = 'SHOW_POPULAR_REQUEST';
export const SHOW_POPULAR_SUCCESS = 'SHOW_POPULAR_SUCCESS';
export const SHOW_POPULAR_FAIL = 'SHOW_POPULAR_FAIL';

export const SHOW_TRENDING_REQUEST = 'SHOW_TRENDING_REQUEST';
export const SHOW_TRENDING_SUCCESS = 'SHOW_TRENDING_SUCCESS';
export const SHOW_TRENDING_FAIL = 'SHOW_TRENDING_FAIL';
